name: sequential_processing
description: A sample application that performs time consuming operations sequentially.
homepage: https://dart.dev/tutorials/language/futures

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
