name: simple_stream
description: A simple application that reads integers from a stream and adds their values together.
homepage: https://dart.dev/tutorials/language/streams

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
