name: httpserver
description: Sample HTTP clients and servers
homepage: https://dart.dev/tutorials/server/httpserver

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  http_server: ^0.9.8+1
  path: ^1.6.2

dev_dependencies:
  test: ^1.6.3
  pedantic: ^1.7.0
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
