name: cmdline
description: A sample application
homepage: https://dart.dev/tutorials/server/cmdline

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: any
  dart_style: any
  test: any

dev_dependencies:
  pedantic: ^1.7.0

executables:
  dcat:
  dgrep:
