name: throw_error
description: A simple app that reads from a stream and throws an error when the loop iterator equals 4.
homepage: https://dart.dev/tutorials/language/streams

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
